export const SEARCH_CONTACTS = 'SEARCH_CONTACTS';

export const UPDATE_LIST = 'UPDATE_LIST';

export const SHOW_BUSINESS_CARD = 'SHOW_BUSINESS_CARD';
export const HIDE_BUSINESS_CARD = 'HIDE_BUSINESS_CARD';

export const UPDATE_SPINNER = 'UPDATE_SPINNER';
